### ISSUE TITLE
portal hub?

### ISSUE THREAD

**Issue by Worgrick** [vampire-studios/Randomly-Adding-Anything-Materials#5]

**Comment by Worgrick** [comment]
I have no idea how to go to this mod's dimensions

**Comment by oliviathevampire** [comment]
what version of the mod?

**Comment by Worgrick** [comment]
1.16

**Comment by Xicad** [comment]
I think it got removed in 1.16 because mojang changed how dimensions work but im not 100% sure

**Comment by oliviathevampire** [comment]
correct
